---
title: "Oklahoma City School Data Explorer"
resource_files:
- schooldistrict.dbf
- schooldistrict.shx
- SchoolDistrict.txt
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: default
---
```{r globals, include = FALSE, verbose=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
#knitr::opts_chunk$set(verbose=FALSE, echo=FALSE, warning=FALSE, message=FALSE)
library(flexdashboard)
library(tidyverse)
library(stringr)
library(data.table)
library(plotly)
library(shiny)
library(leaflet)
library(rgdal)
library(stringr)
library(formattable)
library(ggthemes)
library(DT)

#Importing Data Sets
###############################################################################
principals<-read.csv("principals.csv", header=TRUE)
contact_info<-read.csv("contactinfo.csv", header=TRUE)
enrollment<-read.csv("OKC_enrollment.csv", header=TRUE)
af_grades_df<-read.csv("AFGrades.csv", header=TRUE)
af_grades_df$LetteGrade<-str_trim(af_grades_df$LetteGrade)
af_grades_df$SchoolName<-toupper(af_grades_df$SchoolName)
spi<-read_csv("SchoolPerformanceIndex.csv")
testScores<-read_csv("SchoolTestScores.csv")
testScores_wide<-gather(testScores, Prof, Prct, Advanced:Satisfactory, factor_key=TRUE)
###############################################################################
#setting list names:
###############################################################################
letterGrades<-unique(af_grades_df$LetteGrade)
gradeGroups<-as.list(unique(af_grades_df$LetterGradeGroup))
schools<- unique(enrollment$SiteName)
year<- unique(enrollment$Year)
#grades<-as.list(unique(enrollment$Grade))
grades<-as.list(c("All","Kindergarten","Pre-School",1,2,3,4,5,6,7,8,9,10,11,12))
grade_groups<-as.list(unique(af_grades_df$LetterGradeGroup))
##############################################################################
#Wide Enrollment for graphs
###############################################################################
wEnrollment <- gather(enrollment, Race_Gender, Count, Hispanic_Male:Total, factor_key = TRUE)
wEnrollment<-filter(wEnrollment, Race_Gender !='Total')
wEnrollment <- separate(wEnrollment, Race_Gender,c("Race","Gender"),sep="_")

#leaflet
#shapefile
district<-readOGR("schooldistrict.shp",layer="schooldistrict")
okc_shp<-subset(district, SD_NAME =="Oklahoma City")
#school maker
school_geo<-read_csv("school_geo.csv")
school_lat <- school_geo$Latitude
school_lon <- school_geo$Longitude
school_name<-school_geo$Site
###############################################################################
#Expenditures
expenditures<-read.csv("okcpsExp.csv", header=TRUE)
#Revenues:
revenues<-read.csv("okcpsRev.csv", header=TRUE)
letter.color<-c("#63ed79","#47c1ff","#fcf95a","#ff9900","#ff0000" )
```

District Map
==============================================================================

```{r map, verbose=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
af_grades<-filter(af_grades_df, af_grades_df$Year == max(af_grades_df$Year))
getColor<-function(grades){
  sapply(af_grades$LetterGradeGroup, function(LetterGradeGroup){
    if(LetterGradeGroup=="A"){
      "green"
    } else if(LetterGradeGroup=="B"){
      "blue"
    } else if(LetterGradeGroup=="C"){
      "pink"
    } else if(LetterGradeGroup=="D"){
      "orange"
    } else if(LetterGradeGroup=="F"){
      "red"
    }
  })
}

icons<- awesomeIcons(
  icon='ios-close',
  iconColor='black',
  library='ion',
  markerColor=getColor(af_grades)
)

map <- leaflet()
map<-addTiles(map, 
              group="Oklahoma")
map<- addPolygons(map,
                  group='School Districts',
                  data=okc_shp,
                  weight=1,
                  fillColor="blue")

map <- addAwesomeMarkers(map,
                         lng=af_grades$Longitude,
                         lat=af_grades$Latitude,
                         icon = icons,
                         label = paste(af_grades$SchoolName,": ", af_grades$LetteGrade))
map<-addLegend(map, 
               "topright", 
               labels=c("A Schools","B School","C School","D School","F School"), 
               col=c("#42f456","#42deed","#fcf94b","#ffb649","#e04135"), 
               title="2016 A-F Grade Colors")

map

```

Oklahoma City
==============================================================================

Column{.sidebar}
----------------------------------------------
###Select Grade Year
```{r}
selectInput(
  "gradeYear",
  "Select Year",
  choices=unique(af_grades_df$Year)
)
```

###Select School Level
```{r}

levels <-as.list(unique(af_grades_df$School_Level))
selectInput(
  "schoolLevel",
  "School Level",
  choices= c("All", levels)
)
```

Row
---------------------------------------------
###Number of Schools By Grade 2013-2016
```{r}
af_grades_2<-filter(af_grades_df, af_grades_df$LetterGradeGroup!='N')
af_grades_agg<-count(group_by(af_grades_2,Year,LetterGradeGroup))
names(af_grades_agg)<-c("Year","Letter Grade", "Count")
af_grades_agg$`Letter Grade`<-as.factor(af_grades_agg$`Letter Grade`)

renderPlotly({
  ggplot(af_grades_agg, aes(Year,
                            y=Count, 
                            color=`Letter Grade`)
                            )+
    geom_point()+
    scale_x_discrete("Year")+
    geom_line()+
    xlab("Year")+
    scale_x_discrete(limits=unique(af_grades_agg$Year))+
    ylab("Number of Schools")+
    labs(color="Grade")+
    theme(axis.text.x = element_text(angle = 45),
          axis.text.y=element_text(angle = 45),
          legend.position = "none",
          panel.background = element_rect(fill = "white", color ="white") ,
          panel.grid.major = element_line(color ="light gray",size=.2)
          )+
    scale_colour_manual(values=letter.color)
})
```

###Number of Schools By Letter Grade (Single Year)
```{r}

af_grades2<- reactive({
  if(input$schoolLevel == 'All'){
    x<-filter(af_grades_df, af_grades_df$LetterGradeGroup!='N' & Year == input$gradeYear)
    x
  } else {
    x<-filter(af_grades_df, af_grades_df$LetterGradeGroup!='N' & Year == input$gradeYear & School_Level == input$schoolLevel )
    x 
  }
})

renderPlot({
  af_grades2<-af_grades2()
  ggplot(af_grades2(), aes(LetterGradeGroup, fill=factor(LetterGradeGroup)))+
    geom_bar(stat="count")+
    xlab("Letter Grade Group")+
    ylab("Number of Schools") +
    theme(axis.text.x = element_text(angle = 45),
          axis.text.y=element_text(angle = 45),
          legend.position = "none",
          panel.background = element_rect(fill = "white", color ="white") ,
          panel.grid.major = element_line(color ="light gray",size=.2)
          )+
    scale_fill_manual(values = letter.color)

})
```

Row
---------------------------------------------
###List of Schools and Index Scores
```{r}
gradeGroups <- reactive({
  if(input$schoolLevel == 'All'){
    x<-filter(af_grades_df, af_grades_df$LetterGradeGroup!='N' & Year == input$gradeYear)
    x<-x[,c("Year", "SchoolName", "IndexScore","LetteGrade")]
    x<-x[order(x$IndexScore, decreasing=TRUE),]
    x
    
  } else {
    x<-filter(af_grades_df, af_grades_df$LetterGradeGroup!='N' & Year == input$gradeYear & School_Level == input$schoolLevel )
    x<-x[,c("Year", "SchoolName", "IndexScore","LetteGrade")]
    x<-x[order(x$IndexScore, decreasing=TRUE),]
    x
  }
})
renderDataTable({
  DT::datatable(gradeGroups())
})
```

###District Financials
```{r}

rev_agg <- aggregate(revenues$Revenue, by=list(revenues$Yr), FUN = sum)
names(rev_agg)<- c("Year","Revenue")
exp_agg <-aggregate(expenditures$Expenditure, by=list(expenditures$YR), FUN = sum)
names(exp_agg)<-c("Year","Expenditure")

fin <-left_join(rev_agg,exp_agg, by=c("Year"="Year"))



fin<-gather(fin, source, money, Revenue:Expenditure)

fin$source<-as.factor(fin$source
                      )
renderPlotly({
  ggplot(
    fin,
    aes(
      x=Year,
      y=money,
      #group = cource,
      color =source
    )) +geom_point()+
      geom_line()+
    #geom_area()+
    theme(#axis.text.x = element_text(angle = 45),
          axis.text.y=element_text(angle = 45),
          legend.position = "none",
          panel.background = element_rect(fill = "white", color ="white") ,
          panel.grid.major = element_line(color ="light gray",size=.2)
          ) +
    scale_y_continuous(labels = scales::dollar_format("$"))+
    scale_color_manual(values=c("#ff4a47","#4bf442"))
})
```


School Explorer
==============================================================================

Column {.sidebar}
-------------------------------------
###School Chooser
```{r}
#School Name
selectInput(
  "schools",
  "Select School",
  choices=schools
)

selectInput(
  "year",
  "Select Year",
  choices=year,
  selected=2016
)

selectInput(
  "grade",
  "Select Grade",
  choices =grades,
  selected="All"
)


selectInput(
  "subject",
  "Select Test Subject (for EOI select any grade between 9 and 12)",
  choices=unique(testScores$Subject),
  selected=1
)
```

Row
-------------------------------------
###Student Teacher Ratio
```{r}
student_teacher_ratio<-reactive({
  x<-filter(principals, principals$SchoolName == input$schools)
  y<-filter(wEnrollment,wEnrollment$Year == 2017 & wEnrollment$SiteName == input$schools)
  
  num_teachers<-x$No.Staff
  num_enrolled<-aggregate(as.numeric(y$Count), by=list(y$Year), FUN=sum)
  names(num_enrolled)<-c("Year","Enrolled")
  num_enrolled <- num_enrolled$Enrolled
  
  stRatio <- round(num_enrolled/num_teachers)
  
})

renderValueBox({
  stRatio <-paste0(student_teacher_ratio(), "/1")
  h2(valueBox(stRatio, 
         "(2017) Student-Teacher Ratio",
         color = ifelse(student_teacher_ratio()<16,"green","red"),
         icon="fa-address-book"))
})
```

### Number of Students
```{r}
num_students<-reactive({
  x<-filter(wEnrollment, wEnrollment$SiteName == input$schools & wEnrollment$Year == input$year)
  
  x<-aggregate(x$Count, by=list(x$Year), FUN = sum)
  names(x)<-c("Year","Enrollment")
  
  x$Enrollment
  
})
renderValueBox({
  h2(valueBox(
    num_students(),
    "Number of Enrolled Students",
    icon="fa-id-card"
         ))
})

```

###A-F Letter Grade
```{r}
afgrade<-reactive({
  if(input$year>=2013 & input$year <= 2016){
        x<-filter(af_grades_df, 
                  af_grades_df$SchoolName==input$schools & 
                    af_grades_df$Year == input$year)
        y<-x$LetteGrade
  } else {
    "-"
  }
})


renderValueBox({
  h3(valueBox(
    afgrade(),
    "Letter Grade",
    icon="fa-pencil",
    color=ifelse(grepl(afgrade(),"A")==TRUE,"green",
                 ifelse(grepl(afgrade(),"B")==TRUE,"#4286f4",
                        ifelse(grepl(afgrade(),"C")==TRUE,"#def416",
                        ifelse(grepl(afgrade(),"D")==TRUE,"#f47616",
                               ifelse(grepl(afgrade(),"F")==TRUE,"red","gray")))))
         ))
})
```

###Grades Served
```{r}
gradespan<-reactive({
  x<-filter(enrollment, enrollment$SiteName==input$schools)
  if(min(x$LowGrade)< -0.5){
    minGrade = "Pre-School"
  } else if (min(x$LowGrade) == 0 | min(x$LowGrade)== -0.5){
    minGrade = "Kindergarten"
  } else{
    minGrade = min(x$LowGrade)
  }
  
  maxGrade = max(x$HighGrade)
  paste(minGrade," - ", maxGrade)
})

renderValueBox({
  
  valueBox(
    gradespan(),
    "Grades Served",
    icon="fa-bell",
    color="gray"
  )
  
})
```

Row
-------------------------------

###School Demographics (Single Year)
```{r}
demos<-reactive({
  if(input$grade=='All'){
    x<-filter(wEnrollment, wEnrollment$Year == input$year & wEnrollment$SiteName == input$schools)
    x<-aggregate(x$Count, by=list(x$Race),FUN=sum)
  } else if(input$grade != 'All'){
    x<-filter(wEnrollment, wEnrollment$Year == input$year & wEnrollment$SiteName == input$schools & wEnrollment$Grade == input$grade)
    x<-aggregate(x$Count, by=list(x$Race),FUN=sum)
  }
})

renderPlot({
  ggplot(demos(), 
         aes(x=Group.1, 
             y=x, 
             fill=Group.1))+
    geom_col()+
    ylab("Number of Students")+
    labs(fill="Demographic") +
    theme(#axis.text.x = element_text(angle = 45),
          axis.text.y=element_text(angle = 45),
          axis.title.x=element_blank(),
          legend.position = "none",
          panel.background = element_rect(fill = "white", color ="white") ,
          panel.grid.major = element_line(color ="light gray",size=.2)
          )
})
```


###Demographics Over Time
```{r}
demos_ot<-reactive({
  
  if(input$grade=='All'){
    x<-filter(wEnrollment, wEnrollment$SiteName == input$schools)
    x<-aggregate(x$Count,  by=list("Year" = x$Year, "Demographic"=x$Race),FUN=sum)
    names(x)=c("Year","Demographic","Count")
    #x$Count <-as.factor(x$Count)
    x$Demographic <-as.factor(x$Demographic)
    x
  } else if(input$grade != 'All'){
    x<-filter(wEnrollment,wEnrollment$SiteName == input$schools &wEnrollment$Grade == input$grade)
    x<-aggregate(x$Count,  by=list(x$Year, x$Race),FUN=sum)
    names(x)=c("Year","Demographic","Count")
    #x$Count <-as.factor(x$Count)
        x$Demographic <-as.factor(x$Demographic)

    x
}
  })

renderPlotly({
  demos_ot<-demos_ot()


  ggplotly(ggplot(demos_ot(), 
                  aes(x=Year, 
                      y=Count, 
                      #group=Demographic,
                      color=Demographic))+
             geom_point()+
             geom_line()+
    ylab("Number of Students")+
      labs(color="Demographic")+
      scale_x_continuous(breaks=demos_ot$Year)+
      theme(#axis.text.x = element_text(angle = 45),
          axis.text.y=element_text(angle = 45),
          legend.position = "none",
          panel.background = element_rect(fill = "white", color ="white") ,
          panel.grid.major = element_line(color ="light gray",size=.2),
          axis.text.x = element_text(unique(demos_ot$Year)),
          axis.title.x = element_blank()
          )
    )
})


```


Row
-------------------------------
###Free and Reduced Lunch (FLR)
```{r}
frl<-reactive({
  x<-filter(spi, spi$Site == input$schools)
})

renderPlot({
frl<-frl()
    ggplot(frl(), aes(x=YR, y=FRL))+
      geom_point()+
      geom_line()+
      scale_y_continuous(limits=c(0,1),labels = percent)+
    ylab("Free and Reduced Lunch")+
          scale_x_continuous(breaks=frl$YR)+

      theme(axis.text.x = element_text(angle = 45),
          axis.text.y=element_text(angle = 45),
          axis.title.x=element_blank(),
          legend.position = "none",
          panel.background = element_rect(fill = "white", color ="white") ,
          panel.grid.major = element_line(color ="light gray",size=.2)
          )
  
})

```

###Student Performance - Testing Profecient and Advanced (EOI Tests are not grade specifc )
```{r}
highschool <-c(9,10,11,12)
scores<- reactive({
  if(input$grade == 'All'){
    NULL
  } else if(input$grade %in% highschool){
    filter(testScores_wide, testScores_wide$Site == input$schools & testScores_wide$Subject==input$subject)
  } else if (!input$grade %in% highschool) {
    filter(testScores_wide, testScores_wide$Site == input$schools & testScores_wide$Subject==input$subject & testScores_wide$Grade==input$grade)
  }
})
renderPlot({
  scores<-scores()
  if(is.null(scores())){
    print("Please Select Grade and Subject")
  } else{
     ggplot(scores(), aes(x=YR, y=Prct, group=factor(Prof), fill=factor(Prof)))+geom_col(position = "dodge")+
      scale_y_continuous(limits=c(0,1),labels = percent)+
      scale_x_continuous(breaks=scores$YR)+
      ylab("Percent of students")+
      theme(axis.text.x = element_text(angle = 45),
          axis.text.y=element_text(angle = 45),
          panel.background = element_rect(fill = "white", color ="white") ,
          panel.grid.major = element_line(color ="light gray",size=.2),
          axis.title.x=element_blank(),
          legend.position = "right"
          )+
      labs("Proficiency")+
      scale_fill_manual("proficiency", values=c("Advanced" = "#4fcc30","Satisfactory"="#42d1f4" ))
  }
  
})
```

District Expenditures
===============================================================================

Column {.sidebar}
-------------------------------------------------------
```{r}
#Fund Number

expenditures <- mutate(expenditures, 
                       FundNum_Description = paste(expenditures$FundCode, expenditures$FundDescript,sep = " "),
                       FunctionNum_Description = paste(expenditures$FunctionCode, expenditures$FunctionDescrip,sep = " "),
                       ObjectCode_Description = paste(expenditures$ObjectCode, expenditures$ObjectDescrip ,sep = " "))
funds<-unique(expenditures$FundNum_Description)
func<- unique(expenditures$FunctionNum_Description)
object<-unique(expenditures$ObjectCode_Description)

selectInput(
  "exp_year",
  "Select Year",
  choices = c("All", unique(expenditures$YR))
)

```


Row
----------------------------------------------------
###Total Expenditure
```{r}

totalExp <- reactive({
  
  if(input$exp_year  != 'All'){
    x<-filter(expenditures, YR == input$exp_year)
    x<-aggregate(x$Expenditure, by=list(x$YR), FUN = sum)
    x$x<-formattable::currency(x$x)
    x$x
  } else {
    x<-"-"
  }
})

renderValueBox(
  valueBox(
    h2(totalExp()),
    "Total Expenditure",
    color = "#30dd36",
    icon = "fa-money"
  )
)
```

###Instruction Expenditure
```{r}

instruction <- reactive({
  
  if(input$exp_year  != 'All'){
    x<-filter(expenditures, expenditures$YR == input$exp_year & expenditures$FunctionCode == 1000 )
    x<-aggregate(x$Expenditure, by=list(x$YR), FUN = sum)
    x$x<-formattable::currency(x$x)
    formattable::currency(x$x)
  } else {
    x<-"-"
  }
})
renderValueBox(
  valueBox(
    h2(instruction()),
    "Instruction Expenditure",
    color = "#2faedd",
    icon = "fa-area-chart"
  )
)
```

###Curriculum
```{r}


inst_curr <- reactive({
  
  if(input$exp_year  != 'All'){
    x<-filter(expenditures, expenditures$YR == input$exp_year & expenditures$FunctionCode == 2212)
    x<-aggregate(x$Expenditure, by=list(x$YR), FUN = sum)
    x$x<-formattable::currency(x$x)
    formattable::currency(x$x)
  } else {
    x<-"-"
  }
})

renderValueBox(
  valueBox(
   h2(inst_curr()),
    "Curriculum Development",
    color = "#df7ff9",
    icon = "fa-area-chart"
  )
)
```

###Salary Expenditure
```{r}

salary <- reactive({
  
  if(input$exp_year  != 'All'){
    x<-filter(expenditures, expenditures$YR == input$exp_year & expenditures$ObjectCode == 110 )
    x<-aggregate(x$Expenditure, by=list(x$YR), FUN = sum)
    x$x<-formattable::currency(x$x)

  } else {
    x<-"-"
  }
})

renderValueBox(
  valueBox(
    h2(salary()),
    "Salary Expenditure (110)",
    color = "orange",
    icon = "fa-area-chart"
  )
)

```

Row
-------------------------------------------------------

###Expenditure Table

```{r}
expTable<- reactive({
  
  if(input$exp_year!='All'){
    
    x<- filter(expenditures, YR == input$exp_year)
    
    x<-aggregate(x$Expenditure, 
               by=list(x$YR,
                       x$FundCode, 
                       x$FundDescript, 
                       x$FunctionCode,
                       x$FunctionDescrip,
                       x$ObjectCode,
                       x$ObjectDescrip),
               FUN = sum)

    names(x)<-c("Year",
                "Fund Code",
                "Fund Description",
                "Function Code",
                "Function Description",
                "Object Code",
                "Object Description",
                "Expenditure")
  
    DT::datatable(x,
                  extensions = 'Buttons', options = list(
                    dom = 'Bfrtip',
                    buttons = c('copy', 'csv', 'excel', 'pdf', 'print')))%>%
    DT::formatCurrency("Expenditure")
  
  } else {
    x<-expenditures
    x<-aggregate(x$Expenditure, 
               by=list(x$YR,
                       x$FundCode, 
                       x$FundDescript, 
                       x$FunctionCode,
                       x$FunctionDescrip,
                       x$ObjectCode,
                       x$ObjectDescrip),
               FUN = sum)

    names(x)<-c("Year",
                "Fund Code",
                "Fund Description",
                "Function Code",
                "Function Description",
                "Object Code",
                "Object Description",
                "Expenditure")
  
    DT::datatable(x,
                  extensions = 'Buttons', options = list(
                    dom = 'Bfrtip',
                    buttons = c('copy', 'csv', 'excel', 'pdf', 'print'))) %>%
    DT::formatCurrency("Expenditure")
    }
})

renderDataTable({
  expTable()
})
```

District Revenues
===============================================================================

Column {.sidebar}
-------------------------------------------------------
```{r}

selectInput(
  "rev_year",
  "Select Year",
  choices = c("All", unique(revenues$Yr))
)

```


Row
----------------------------------------------------
###Total Revenue
```{r}

totalRev <- reactive({
  
  if(input$rev_year  != 'All'){
    x<-filter(revenues, Yr == input$rev_year)
    x<-aggregate(x$Revenue, by=list(x$Yr), FUN = sum)
    x$x<-formattable::currency(x$x)
    h2(x$x)
  } else {
    x<-"-"
  }
})

renderValueBox(
  valueBox(
    totalRev(),
    "Total Revenue",
    color = "#30dd36",
    icon = "fa-money"
  )
)
```


###Ad Valorem
```{r}

adValorem <- reactive({
  if(input$rev_year!="All"){
      x<- filter(revenues, revenues$Yr == input$rev_year & (revenues$ResourceCode == 1110 | revenues$ResourceCode == 1120))
  x<-aggregate(x$Revenue, by = list(x$Yr), FUN = sum)
  x$x<-formattable::currency(x$x)

  h2(x$x)
  } else {
    "-"
  }
  
})
renderValueBox(
  valueBox(
    adValorem(),
    "Total Ad Valorem Revenue",
    color = "#2faedd",
    icon = "fa-area-chart"
  )
)
```

###Motor Vehicle
```{r}

grossProduction <- reactive({
  if(input$rev_year!="All"){
      x<- filter(revenues, revenues$Yr == input$rev_year & revenues$ResourceCode==3110)
      y<-h2(formattable::currency(x$Revenue))
  } else {
    "-"
  }
})


renderValueBox(
  valueBox(
    grossProduction(),
    "Gross Poduction Revenue",
    color = "#df7ff9",
    icon = "fa-area-chart"
  )
)
```

###Gross Production
```{r}


motorVehicle <- reactive({
  if(input$rev_year!="All"){
      x<- filter(revenues, revenues$Yr == input$rev_year & revenues$ResourceCode==3120)
      y<-h2(formattable::currency(x$Revenue))
  } else {
    "-"
  }
})
  
renderValueBox(
  valueBox(
    motorVehicle(),
    "Motor Vehicle Tax Revenue",
    color = "orange",
    icon = "fa-area-chart"
  )
)

```

Row
-------------------------------------------------------
```{r}
r <- select(revenues, Yr, FundCode, FundDescrip, ResourceCode, ResourceDescrip, Revenue )

rt<- reactive({
    
  if(input$rev_year!='All'){
    
    x<- filter(revenues, Yr == input$rev_year)
    
    x<-aggregate(x$Revenue, 
               by=list(x$Yr,
                       x$FundCode, 
                       x$FundDescrip, 
                       x$ResourceCode,
                       x$ResourceDescrip),
               FUN = sum)

    names(x)<-c("Year",
                "Fund Code",
                "Fund Description",
                "Resource Code",
                "Resource Description",
                "Revenue")
  
    DT::datatable(x,
                  extensions = 'Buttons', options = list(
                    dom = 'Bfrtip',
                    buttons = c('copy', 'csv', 'excel', 'pdf', 'print')))%>%
      
    DT::formatCurrency("Revenue")
  
  } else {
    x<-revenues
    x<-aggregate(x$Revenue, 
               by=list(x$Yr,
                       x$FundCode, 
                       x$FundDescrip, 
                       x$ResourceCode,
                       x$ResourceDescrip),
               FUN = sum)

    names(x)<-c("Year",
                "Fund Code",
                "Fund Description",
                "Resource Code",
                "Resource Description",
                "Revenue")
  
    DT::datatable(x,
                  extensions = 'Buttons', options = list(
                    dom = 'Bfrtip',
                    buttons = c('copy', 'csv', 'excel', 'pdf', 'print'))) %>%
    DT::formatCurrency("Revenue")
    
  
  
}
  })

renderDataTable({
  rt()
})
```

