---
title: "test2"
author: "Thomas Curran"
date: "5/25/2017"
output: html_document
---
```{r verbose = FALSE, echo=FALSE}
library(tidyverse)
expenditures<-read_csv("okcpsExp.csv")
```

```{r}
library(tidyverse)
library(plotly)
expenditures<-read_csv("okcpsExp.csv")

expenditures<- filter(expenditures, expenditures$YR == 2015)

expenditures<-aggregate(expenditures$Expenditure,
                        by = list("Year" = expenditures$YR, 
                                  "FundCode" = expenditures$FundCode),
                        FUN = sum
                        )
expenditures <- mutate(expenditures, 
                       "Fund.Name" = paste("Fund",
                                           expenditures$FundCode, 
                                           sep = " ")
                       )





  ggplot(
    expenditures,
    aes(x=expenditures$Fund.Name,
        y=expenditures$x,
        fill = factor(Fund.Name))
  ) + 
    geom_bar(stat = "identity") + 
    scale_x_discrete("Fund Code")+
    ylab("Expenditures in Dollars")+
    scale_y_continuous(labels = scales::dollar_format("$"))+
    xlab("Fund Number")+
    ggtitle(paste("Total Expenditure By Fund", unique(expenditures$Year), sep = " "))+
    theme(axis.text.x = element_text(angle = 45),
          axis.text.y=element_text(angle = 45),
          legend.position = "none",
          panel.background = element_rect(fill = "white", color ="white") ,
          panel.grid.major = element_line(color ="light gray",size=.2)
          )


```
```{r}
revenues <- read_csv("okcpsRev.csv")

revenues <- select(revenues, Yr, FundCode, FundDescrip, ResourceCode, ResourceDescrip, Revenue)

revenues<-aggregate(revenues$Revenue, by=list(revenues$Yr, revenues$FundCode, revenues$FundDescrip, revenues$ResourceCode), FUN = sum)

DT::datatable(revenues)%>%
  DT::formatCurrency("x")
```

```{r}

revenues<-read_csv("okcpsRev.csv")
#revenues<-filter(revenues, FundCode == 11)
z<-aggregate(revenues$Revenue, by=list(revenues$Yr), FUN = sum)
names(z)<-c("Year","Total Revenue")
#ggplot(z, aes(x=z$`Fund Code`,y=z$`Total Revenue`, group=factor(z$`Fund Code`)))+geom_bar(stat="identity")

ggplot(
  z,
  aes(
    y=z$`Total Revenue`,
    x=z$Year)
  ) + 
  geom_point()+
  geom_line()+
  theme(axis.text.x = element_text(angle = 45),
          axis.text.y=element_text(angle = 45),
          legend.position = "none",
          panel.background = element_rect(fill = "white", color ="white") ,
          panel.grid.major = element_line(color ="light gray",size=.2)
          )+
    ylab("Expenditures in Dollars")+
    scale_y_continuous(labels = scales::dollar_format("$"))+
    xlab("Fund Number")
```
```{r}
rev_agg <- aggregate(revenues$Revenue, by=list(revenues$Yr), FUN = sum)
names(rev_agg)<- c("Year","Revenue")
exp_agg <-aggregate(expenditures$Expenditure, by=list(expenditures$YR), FUN = sum)
names(exp_agg)<-c("Year","Expenditure")

rev_agg

exp_agg




fin <-left_join(rev_agg,exp_agg, by=c("Year"="Year"))
fin<-gather(fin, source, money, Revenue:Expenditure)

fin
```

